### ISSUE TITLE
Compiling error with Arduino IDE 1.68

### ISSUE THREAD

**Issue by Gabapentin** [soligen2010/RC_RX_CABELL_V3_FHSS#2]
Hi Dennis, 
sorry for annoyance
I have tried to compile the sketch on a fresh Arduino IDE 1.68 installation
but the compiler give me some errors:

-----------------------------------------------------------------------------------------------------------
Arduino:1.6.8 (Windows 7), Scheda:"Arduino Pro or Pro Mini, ATmega328 (5V, 16 MHz)"

sketch\MyServo.cpp: In function 'void MyServoInterruptOneProcessing()':

sketch\MyServo.cpp:85:43: warning: 'void MyServoInterruptOneProcessing()' was declared 'extern' and later 'static' [-fpermissive]

 static void MyServoInterruptOneProcessing()

    ^

In file included from sketch\MyServo.cpp:30:0:

sketch\MyServo.h:125:6: note: previous declaration of 'void MyServoInterruptOneProcessing()'

 void MyServoInterruptOneProcessing();

                 ^

sketch\MyServo.cpp: At global scope:

sketch\MyServo.cpp:189:39: warning: unused parameter 'timer' [-Wunused-parameter]

 static void finISR(timer16_Sequence_t timer)

                                                                 ^

sketch\RX.cpp:35:26: fatal error: ClickEncoder.h: No such file or directory

 #include <ClickEncoder.h>

                        ^

compilation terminated.

Thanks a lot in advance for your reply

BR's Pat

**Comment by soligen2010** [comment]
Sorry for the delay getting back to you.  I have been down with the flu.

I use Arduino 1.8.0 and it compiles.  Can you please try removing static from

static void MyServoInterruptOneProcessing()

and see if they solves it on 1.6.8.

Thanks

**Comment by Gabapentin** [comment]
Thanks a lot Dennis 

don't worry I'm not in a hurry

In the meantime I've removed static and installed missing "encoder" library
 
now seems to be working 

get well soon!

BR's Pat

**Comment by soligen2010** [comment]
I am glad that worked.  I made the change and also added the encoder library to the comments as a dependency.

As this appears resolved, I am closing this issue.

**Comment by soligen2010** [comment]
FYI, in an effort to lighten up the code a bit, the encoder library is no longer needed
