### ISSUE TITLE
Feature request: No pulse failsafe option

### ISSUE THREAD

**Issue by qubicllj** [soligen2010/RC_RX_CABELL_V3_FHSS#4]
It is more convenient to setup failfafe in flight controller, no pulse failsafe is a good choice in this scene

**Comment by soligen2010** [comment]
Thanks for your suggestion.

Can you provide more details on how this would need to be implemented?  Are we talking about the SBUS output or the servo outputs?

SBUS has a fail-safe flag in the packet, and the receiver sets this flag appropriately on SBUS output when there is a failsafe.  Iis this what no-pulses is supposed to do? Do you know if flight controllers honor this flag?

**Comment by qubicllj** [comment]
Just stop sending signals to the flight controller in ppm mode;
Cleanflight and Betaflight honor the sbus fail-safe flag, the cleanflight community has implemented it, https://github.com/cleanflight/cleanflight/issues/2549

**Comment by soligen2010** [comment]
I just uploaded a new version with no-pulses capability.  It seems to work but has very limited testing at this point.  Please test if you can.  You will need to use my fork of Multi-protocol with the latest RX code as I have not merged my MultiProtocol changes back yet.  In this mode both PPM signals and SBUS signals are stopped on failsafe.

**Comment by qubicllj** [comment]
OK, i will test it later.

**Comment by qubicllj** [comment]
I have tested the latest firmware, the no-pulse works as expected.

By the way is the D4 ( SchematicWithDiversityWithSBUS.png ) optional if only one module is connected ?

**Comment by soligen2010** [comment]
Thanks for testing it.

Yes, D4 is not needed if only one NRF24L01 is connected

**Comment by soligen2010** [comment]
Closing as this feature is complete
