### ISSUE TITLE
Support for Deviation TX with NRF24

### ISSUE THREAD

**Issue by techboycr** [soligen2010/RC_RX_CABELL_V3_FHSS#5]
This is not and issue with this project.

Just want to know if anyone know if this protocol is present in Deviation firmware with nrf24 radio.

Otherwise, where can I find the protocol spec to post them in the Deviation Forums and start develpment thread for the protocol.

Thanks!

**Comment by soligen2010** [comment]
I am not aware of it being added to Deviation.  There have been several people who have forked the project, so if they are working on it, hopefully they will chime in.

The main page of this project has all the documentation.  For an implementation of the TX side, you can look at the Multiprotocol module [here](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Multiprotocol/CABELL_nrf224l01.ino)

**Comment by techboycr** [comment]
Coooool!
I get into this ASAP, will be my first time doing this kind of thing... But I am very optimistic, let do this!

**Comment by techboycr** [comment]
In which version of FHSS did you base this protocol??
S? A? 3?

**Comment by soligen2010** [comment]
This protocol is not based on any other.  It is completely independently created.
